# Generated by Django 2.2.6 on 2019-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0002_auto_20191003_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='image',
            field=models.ImageField(blank=True, upload_to='classic'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='image',
            field=models.ImageField(blank=True, upload_to='premium'),
        ),
    ]
