# Generated by Django 2.2.6 on 2019-10-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0003_auto_20191003_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='image',
            new_name='classic',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='image',
            new_name='premium',
        ),
    ]
