# Generated by Django 2.2.6 on 2019-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0004_auto_20191003_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classic_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premium_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
