# Generated by Django 2.2.6 on 2019-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0005_classic_description_premium_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_top', models.ImageField(blank=True, upload_to='main_top', verbose_name='Изображение')),
                ('info_top', models.CharField(db_index=True, max_length=250, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Изображение в шапке сайта',
            },
        ),
        migrations.DeleteModel(
            name='Classic_Description',
        ),
        migrations.DeleteModel(
            name='Premium_Description',
        ),
        migrations.AlterModelOptions(
            name='classic',
            options={'verbose_name': 'Список подарков серии "Классика"', 'verbose_name_plural': 'Классика'},
        ),
        migrations.AlterModelOptions(
            name='premium',
            options={'verbose_name': 'Список подарков серии "Премиум"', 'verbose_name_plural': 'Премиум'},
        ),
        migrations.AlterField(
            model_name='classic',
            name='classic',
            field=models.ImageField(blank=True, upload_to='classic', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='content',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='gram',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='content',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='gram',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='premium',
            field=models.ImageField(blank=True, upload_to='premium', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
    ]
