# Generated by Django 2.2.6 on 2019-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0006_auto_20191004_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(db_index=True, max_length=150, verbose_name='Информация')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintop',
            name='info_top',
        ),
    ]
