# Generated by Django 2.2.6 on 2019-10-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0008_auto_20191004_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
