# Generated by Django 2.2.6 on 2019-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0009_auto_20191004_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logotype',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотип сайта'},
        ),
        migrations.AlterField(
            model_name='maintop',
            name='main_top',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
