# Generated by Django 2.2.6 on 2019-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0010_auto_20191007_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='content',
        ),
        migrations.AddField(
            model_name='classic',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='classic',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Название'),
        ),
    ]
