# Generated by Django 2.2.6 on 2019-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0011_auto_20191008_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='names',
        ),
        migrations.AddField(
            model_name='classic',
            name='content',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
    ]
