# Generated by Django 2.2.6 on 2019-10-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0012_auto_20191008_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='content2',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
    ]
