# Generated by Django 2.2.6 on 2019-10-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0013_classic_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='content',
        ),
        migrations.AddField(
            model_name='classic',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='classic',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='premium',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='premium',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Название'),
        ),
    ]
