# Generated by Django 2.2.6 on 2019-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0014_auto_20191009_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='descript',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='classic',
            name='manufact',
            field=models.TextField(blank=True, db_index=True, verbose_name='Изобр. производителя'),
        ),
        migrations.AddField(
            model_name='classic',
            name='photos',
            field=models.TextField(blank=True, db_index=True, verbose_name='Фото конфеты'),
        ),
        migrations.AddField(
            model_name='premium',
            name='descript',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='premium',
            name='manufact',
            field=models.TextField(blank=True, db_index=True, verbose_name='Изобр. производителя'),
        ),
        migrations.AddField(
            model_name='premium',
            name='photos',
            field=models.TextField(blank=True, db_index=True, verbose_name='Фото конфеты'),
        ),
    ]
