# Generated by Django 2.2.6 on 2019-10-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0015_auto_20191010_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('photos', models.ImageField(blank=True, upload_to='social', verbose_name='Фото')),
                ('descript', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('manufact', models.ImageField(blank=True, upload_to='manufactures', verbose_name='Производитель')),
                ('counts', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('slug', models.SlugField(unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Список сладостей',
                'verbose_name_plural': 'Сладости',
            },
        ),
        migrations.RemoveField(
            model_name='classic',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='manufact',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='names',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='manufact',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='names',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='photos',
        ),
        migrations.AlterField(
            model_name='classic',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
