# Generated by Django 2.2.6 on 2019-10-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0017_auto_20191010_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweets',
            old_name='slug',
            new_name='sl',
        ),
    ]
