# Generated by Django 2.2.6 on 2019-10-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0018_auto_20191010_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='sl',
        ),
    ]
