# Generated by Django 2.2.6 on 2019-10-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0019_remove_sweets_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='classic',
            name='descript',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='classic',
            name='manufact',
            field=models.TextField(blank=True, db_index=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='classic',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='classic',
            name='photos',
            field=models.TextField(blank=True, db_index=True, verbose_name='Фото'),
        ),
    ]
