# Generated by Django 2.2.6 on 2019-10-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0020_auto_20191011_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='manufact',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='names',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='photos',
        ),
    ]
