# Generated by Django 2.2.6 on 2019-10-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0022_sweets_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='slug',
        ),
    ]
