# Generated by Django 2.2.6 on 2019-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0023_remove_sweets_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='counts2',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
    ]
