# Generated by Django 2.2.6 on 2019-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0025_remove_sweets_counts2'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Названия сладостей подарка (через запятую)'),
        ),
        migrations.AddField(
            model_name='premium',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Названия сладостей подарка (через запятую)'),
        ),
    ]
