# Generated by Django 2.2.6 on 2019-10-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0026_auto_20191012_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweets',
        ),
        migrations.AddField(
            model_name='classic',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='classic',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='classic',
            name='manufactures',
            field=models.TextField(blank=True, db_index=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='classic',
            name='sweets',
            field=models.TextField(blank=True, db_index=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='premium',
            name='counts',
            field=models.TextField(blank=True, db_index=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='premium',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='premium',
            name='manufactures',
            field=models.TextField(blank=True, db_index=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='premium',
            name='sweets',
            field=models.TextField(blank=True, db_index=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='classic',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Названия сладостей'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='names',
            field=models.TextField(blank=True, db_index=True, verbose_name='Названия сладостей'),
        ),
    ]
