# Generated by Django 2.2.6 on 2019-10-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0030_auto_20191014_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='slug',
        ),
        migrations.AddField(
            model_name='classic',
            name='descript',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
    ]
