# Generated by Django 2.2.6 on 2019-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0031_auto_20191014_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='descript',
        ),
        migrations.AddField(
            model_name='classic',
            name='n1',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='classic',
            name='n2',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
    ]
