# Generated by Django 2.2.6 on 2019-10-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0032_auto_20191014_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='i',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
    ]
