# Generated by Django 2.2.6 on 2019-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0033_classic_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='i',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='n1',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='n2',
        ),
        migrations.AddField(
            model_name='sweets',
            name='ns',
            field=models.ManyToManyField(to='vp.Classic'),
        ),
    ]
