# Generated by Django 2.2.6 on 2019-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0034_auto_20191015_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='ns',
        ),
        migrations.AddField(
            model_name='classic',
            name='ns',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
