# Generated by Django 2.2.6 on 2019-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0035_auto_20191015_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweets',
            options={'verbose_name': 'Список сладостей', 'verbose_name_plural': 'Сладости'},
        ),
        migrations.RenameField(
            model_name='classic',
            old_name='ns',
            new_name='lists',
        ),
        migrations.AddField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
