# Generated by Django 2.2.6 on 2019-10-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0036_auto_20191015_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='classic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='premium',
            new_name='image',
        ),
    ]
