# Generated by Django 2.2.6 on 2019-10-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0040_auto_20191015_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='images',
            new_name='image',
        ),
    ]
