# Generated by Django 2.2.6 on 2019-10-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0042_auto_20191015_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='classic',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='premium',
            new_name='media',
        ),
    ]
