# Generated by Django 2.2.6 on 2019-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0043_auto_20191015_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='lists',
        ),
        migrations.AddField(
            model_name='sweets',
            name='lists',
            field=models.ManyToManyField(to='vp.Classic'),
        ),
    ]
