# Generated by Django 2.2.6 on 2019-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0044_auto_20191015_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='lists',
        ),
        migrations.AddField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
        migrations.AddField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
