# Generated by Django 2.2.6 on 2019-10-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0050_auto_20191015_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='sweets',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='vp.Sweets'),
        ),
    ]
