# Generated by Django 2.2.6 on 2019-10-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0051_auto_20191015_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='sweets',
        ),
        migrations.AddField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
