# Generated by Django 2.2.6 on 2019-10-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0053_auto_20191015_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='lists',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vp.Sweets'),
        ),
    ]
