# Generated by Django 2.2.6 on 2019-10-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0054_auto_20191015_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='lists',
            new_name='lists_id',
        ),
    ]
