# Generated by Django 2.2.6 on 2019-10-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0055_auto_20191015_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='lists_id',
        ),
        migrations.AddField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
