# Generated by Django 2.2.6 on 2019-10-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0056_auto_20191015_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='classic',
            name='sweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vp.Sweet'),
        ),
    ]
