# Generated by Django 2.2.6 on 2019-10-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0058_auto_20191016_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='classic',
            name='typebox',
        ),
        migrations.AddField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
        migrations.AddField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
        migrations.DeleteModel(
            name='TypeBox',
        ),
        migrations.AddField(
            model_name='classic',
            name='sweet',
            field=models.ForeignKey(null='111', on_delete=django.db.models.deletion.CASCADE, to='vp.Sweet'),
            preserve_default='111',
        ),
    ]
