# Generated by Django 2.2.6 on 2019-10-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0060_auto_20191016_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='sweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vp.Classic', verbose_name='Вид упаковки'),
        ),
    ]
