# Generated by Django 2.2.6 on 2019-10-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0062_auto_20191016_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweet',
        ),
        migrations.RemoveField(
            model_name='classic',
            name='lists',
        ),
        migrations.AlterField(
            model_name='classic',
            name='sweets',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='vp.Sweets'),
        ),
    ]
