# Generated by Django 2.2.6 on 2019-10-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0063_auto_20191016_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='sweets',
            new_name='boxes',
        ),
    ]
