# Generated by Django 2.2.6 on 2019-10-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0065_auto_20191016_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='boxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vp.Sweets'),
        ),
    ]
