# Generated by Django 2.2.6 on 2019-10-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0067_auto_20191016_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classic',
            old_name='boxes',
            new_name='sweets',
        ),
    ]
