# Generated by Django 2.2.6 on 2019-10-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0069_auto_20191016_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='sweets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vp.Sweets', verbose_name='Сладости'),
        ),
    ]
