# Generated by Django 2.2.6 on 2019-10-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0070_auto_20191016_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Список сладостей',
                'verbose_name_plural': 'Сладости',
            },
        ),
        migrations.AddField(
            model_name='sweets',
            name='sweets',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='vp.Rubric', verbose_name='Сладости'),
        ),
    ]
