# Generated by Django 2.2.6 on 2019-10-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0071_auto_20191016_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweets',
            name='sweets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vp.Rubric'),
        ),
    ]
