# Generated by Django 2.2.6 on 2019-10-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0072_auto_20191016_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='sweets',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
