# Generated by Django 2.2.6 on 2019-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0073_auto_20191016_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='classic',
            name='sweets',
        ),
        migrations.AddField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
        migrations.AddField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(to='vp.Sweets'),
        ),
    ]
