# Generated by Django 2.2.6 on 2019-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0074_auto_20191016_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
