# Generated by Django 2.2.6 on 2019-10-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0075_sweets_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweets',
            old_name='slug',
            new_name='slugs',
        ),
    ]
