# Generated by Django 2.2.6 on 2019-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0076_auto_20191016_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweets',
            name='slugs',
            field=models.SlugField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
