# Generated by Django 2.2.6 on 2019-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0077_auto_20191016_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweet',
        ),
        migrations.RenameField(
            model_name='sweets',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(related_name='_classic_lists_+', to='vp.Sweets'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(related_name='_premium_lists_+', to='vp.Sweets'),
        ),
    ]
