# Generated by Django 2.2.6 on 2019-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0078_auto_20191020_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='slug',
        ),
        migrations.AddField(
            model_name='sweets',
            name='number',
            field=models.CharField(db_index=True, default='0', max_length=10, verbose_name='Номер подарка'),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='fm',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
        migrations.AlterField(
            model_name='sweets',
            name='fs',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
    ]
