# Generated by Django 2.2.6 on 2019-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0079_auto_20191020_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetsClassic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('sweet', models.CharField(db_index=True, max_length=150, verbose_name='Название фото')),
                ('media', models.ImageField(blank=True, upload_to='sweets/classic', verbose_name='Изображение')),
                ('descript', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('manufact', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('counts', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('number', models.CharField(db_index=True, default='0', max_length=10, verbose_name='Номер подарка')),
            ],
            options={
                'verbose_name': 'Список сладостей',
                'verbose_name_plural': 'Сладости серии "Классика"',
            },
        ),
        migrations.CreateModel(
            name='SweetsPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('sweet', models.CharField(db_index=True, max_length=150, verbose_name='Название фото')),
                ('media', models.ImageField(blank=True, upload_to='sweets/premium', verbose_name='Изображение')),
                ('descript', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('manufact', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('counts', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('number', models.CharField(db_index=True, default='0', max_length=10, verbose_name='Номер подарка')),
            ],
            options={
                'verbose_name': 'Список сладостей',
                'verbose_name_plural': 'Сладости серии "Премиум"',
            },
        ),
        migrations.DeleteModel(
            name='Sweets',
        ),
        migrations.AlterField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(related_name='_classic_lists_+', to='vp.SweetsClassic'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(related_name='_premium_lists_+', to='vp.SweetsPremium'),
        ),
    ]
