# Generated by Django 2.2.6 on 2019-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0080_auto_20191020_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweetsclassic',
            name='sweet',
        ),
        migrations.RemoveField(
            model_name='sweetspremium',
            name='sweet',
        ),
    ]
