# Generated by Django 2.2.6 on 2019-10-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0081_auto_20191020_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweetsclassic',
            name='media',
        ),
        migrations.RemoveField(
            model_name='sweetspremium',
            name='media',
        ),
        migrations.AddField(
            model_name='sweetsclassic',
            name='fm',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
        migrations.AddField(
            model_name='sweetsclassic',
            name='fs',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
        migrations.AddField(
            model_name='sweetsclassic',
            name='sweet',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название фото'),
        ),
        migrations.AddField(
            model_name='sweetspremium',
            name='fm',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
        migrations.AddField(
            model_name='sweetspremium',
            name='fs',
            field=models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото'),
        ),
        migrations.AddField(
            model_name='sweetspremium',
            name='sweet',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='sweetsclassic',
            name='number',
            field=models.CharField(db_index=True, default=0, max_length=10, verbose_name='Номер подарка'),
        ),
        migrations.AlterField(
            model_name='sweetspremium',
            name='number',
            field=models.CharField(db_index=True, default=0, max_length=10, verbose_name='Номер подарка'),
        ),
    ]
