# Generated by Django 2.2.6 on 2019-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0082_auto_20191020_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetsclassic',
            name='sweet',
            field=models.CharField(db_index=True, default='Конфета', max_length=150, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='sweetspremium',
            name='sweet',
            field=models.CharField(db_index=True, default='Конфета', max_length=150, verbose_name='Название фото'),
        ),
    ]
