# Generated by Django 2.2.6 on 2019-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0083_auto_20191020_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('sweet', models.CharField(db_index=True, max_length=150, verbose_name='Название фото')),
                ('fs', models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото')),
                ('descript', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('manufact', models.CharField(db_index=True, max_length=150, verbose_name='Производитель')),
                ('fm', models.CharField(db_index=True, default='jpg', max_length=10, verbose_name='Формат фото')),
                ('counts', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('number', models.CharField(db_index=True, default='0', max_length=10, verbose_name='Номер подарка')),
            ],
            options={
                'verbose_name': 'Список сладостей',
                'verbose_name_plural': 'Сладости',
            },
        ),
        migrations.DeleteModel(
            name='SweetsClassic',
        ),
        migrations.DeleteModel(
            name='SweetsPremium',
        ),
        migrations.AlterField(
            model_name='classic',
            name='lists',
            field=models.ManyToManyField(related_name='_classic_lists_+', to='vp.Sweets'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='lists',
            field=models.ManyToManyField(related_name='_premium_lists_+', to='vp.Sweets'),
        ),
    ]
