# Generated by Django 2.2.6 on 2019-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0085_auto_20191020_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='classic',
            name='series',
            field=models.CharField(db_index=True, default='Классика', max_length=50, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='premium',
            name='series',
            field=models.CharField(db_index=True, default='Премиум', max_length=50, verbose_name='Серия'),
        ),
    ]
