# Generated by Django 2.2.6 on 2019-10-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0086_auto_20191020_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='series',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Серия'),
        ),
    ]
