# Generated by Django 2.2.6 on 2019-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0087_sweets_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, upload_to='classic', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения подарков серии "Классика"',
            },
        ),
        migrations.AlterField(
            model_name='classic',
            name='media',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Изображение'),
        ),
    ]
