# Generated by Django 2.2.6 on 2019-10-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0089_auto_20191020_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, upload_to='manufactures', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения производителей',
            },
        ),
        migrations.CreateModel(
            name='SweetsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, upload_to='sweets', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения сладостей',
            },
        ),
        migrations.RemoveField(
            model_name='sweets',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='sweets',
            name='fs',
        ),
    ]
