# Generated by Django 2.2.6 on 2019-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0090_auto_20191020_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactures',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
    ]
