# Generated by Django 2.2.6 on 2019-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0091_manufactures_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicimg',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='premiumimg',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sweetsimg',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
    ]
