# Generated by Django 2.2.6 on 2019-10-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0092_auto_20191020_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='sweet',
        ),
    ]
