# Generated by Django 2.2.6 on 2019-10-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0093_remove_sweets_sweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Типы упаковок',
                'verbose_name_plural': 'Тип упаковки',
            },
        ),
        migrations.AlterModelOptions(
            name='classicimg',
            options={'verbose_name': 'Название | Изображение', 'verbose_name_plural': 'Изображения подарков серии "Классика"'},
        ),
        migrations.AlterModelOptions(
            name='premiumimg',
            options={'verbose_name': 'Название | Изображение', 'verbose_name_plural': 'Изображения подарков серии "Премиум"'},
        ),
        migrations.AddField(
            model_name='classic',
            name='typebox',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vp.TypeBox'),
        ),
        migrations.AddField(
            model_name='premium',
            name='typebox',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vp.TypeBox'),
        ),
    ]
