# Generated by Django 2.2.6 on 2019-10-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0094_auto_20191021_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classic',
            name='typebox',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='vp.TypeBox'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='typebox',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='vp.TypeBox'),
        ),
    ]
