# Generated by Django 2.2.6 on 2019-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0095_auto_20191021_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classic',
            name='typebox',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='typebox',
        ),
        migrations.AddField(
            model_name='classic',
            name='type_box',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Тип упаковки'),
        ),
        migrations.AddField(
            model_name='premium',
            name='type_box',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Тип упаковки'),
        ),
        migrations.DeleteModel(
            name='TypeBox',
        ),
    ]
