# Generated by Django 2.2.6 on 2019-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0098_auto_20191024_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='', verbose_name='Изображения сайта')),
            ],
            options={
                'verbose_name': 'Изображения сайта',
                'verbose_name_plural': 'Изображения сайта',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ImageField(blank=True, upload_to='main', verbose_name='Изображение')),
                ('logo', models.ImageField(blank=True, upload_to='main', verbose_name='Логотип сайта')),
                ('bg', models.ImageField(blank=True, upload_to='main', verbose_name='Фон сайта')),
            ],
            options={
                'verbose_name': 'Изображение в шапке сайта',
                'verbose_name_plural': 'Изображение в шапке сайта',
            },
        ),
        migrations.DeleteModel(
            name='Logotype',
        ),
        migrations.DeleteModel(
            name='MainTop',
        ),
    ]
