# Generated by Django 2.2.6 on 2019-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0102_auto_20191024_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='header',
        ),
        migrations.AddField(
            model_name='title',
            name='name_page',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название (title) страницы сайта'),
        ),
    ]
