# Generated by Django 2.2.6 on 2019-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0103_auto_20191024_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='url',
            field=models.SlugField(default='', unique=True, verbose_name='Адрес страницы'),
        ),
    ]
