# Generated by Django 2.2.6 on 2019-10-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0104_title_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='url',
            new_name='slug',
        ),
    ]
