# Generated by Django 2.2.6 on 2019-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0105_auto_20191024_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Страницы сайта', 'verbose_name_plural': 'Страницы сайта'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
        migrations.AddField(
            model_name='title',
            name='descript_classic',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Краткое описание для классики'),
        ),
        migrations.AddField(
            model_name='title',
            name='descript_premium',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Краткое описание для премиум'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name_page',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Краткое описание страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название страницы сайта'),
        ),
    ]
