# Generated by Django 2.2.6 on 2019-10-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0106_auto_20191024_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'ID | Страницы сайта', 'verbose_name_plural': 'Страницы сайта'},
        ),
        migrations.AlterField(
            model_name='title',
            name='descript_classic',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание для классики'),
        ),
        migrations.AlterField(
            model_name='title',
            name='descript_premium',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание для премиум'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h2',
            field=models.CharField(default='', max_length=150, verbose_name='Заголовок h2 страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h3_classic',
            field=models.CharField(default='', max_length=150, verbose_name='Заголовок h3 для классики'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h3_premium',
            field=models.CharField(default='', max_length=150, verbose_name='Заголовок h3 для премиум'),
        ),
    ]
