# Generated by Django 2.2.6 on 2019-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0108_title_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='descript_classic',
            field=models.TextField(default='', verbose_name='Краткое описание для классики'),
        ),
        migrations.AlterField(
            model_name='title',
            name='descript_premium',
            field=models.TextField(default='', verbose_name='Краткое описание для премиум'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description2',
            field=models.TextField(default='', verbose_name='Краткое описание сайта 2'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Название страницы сайта'),
        ),
    ]
