# Generated by Django 2.2.6 on 2019-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0109_auto_20191025_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='descript_classic',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание для классики'),
        ),
        migrations.AlterField(
            model_name='title',
            name='descript_premium',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание для премиум'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description2',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание сайта 2'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Заголовок h1 страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Заголовок h2 страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h3_classic',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Заголовок h3 для классики'),
        ),
        migrations.AlterField(
            model_name='title',
            name='h3_premium',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Заголовок h3 для премиум'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name_page',
            field=models.CharField(blank=True, db_index=True, default='Сладкие Новогодние подарки для детей 2020', max_length=150, verbose_name='Краткое описание страницы сайта'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название страницы сайта'),
        ),
    ]
