# Generated by Django 2.2.6 on 2019-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0110_auto_20191025_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=150, verbose_name='Название')),
                ('names', models.CharField(db_index=True, default='', max_length=250, verbose_name='Выделенный текст')),
                ('texts', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('media', models.ImageField(blank=True, upload_to='blocks', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Названия блоков',
                'verbose_name_plural': 'Изображения блоков',
            },
        ),
    ]
