# Generated by Django 2.2.6 on 2019-10-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0111_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=150, verbose_name='Тип упаковки')),
                ('media', models.ImageField(blank=True, upload_to='types', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'ID | Тип упаковки',
                'verbose_name_plural': 'Типы упаковок',
            },
        ),
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name': 'ID | Названия блоков', 'verbose_name_plural': 'Изображения блоков'},
        ),
        migrations.RemoveField(
            model_name='blocks',
            name='names',
        ),
        migrations.AlterField(
            model_name='blocks',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=250, verbose_name='Выделенный текст'),
        ),
    ]
