# Generated by Django 2.2.6 on 2019-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0112_auto_20191025_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNumbersLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, default='', max_length=150, verbose_name='Город')),
                ('phone', models.CharField(db_index=True, default='', max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номера телефонов слева в шапке сайта',
                'verbose_name_plural': 'Номера телефонов слева в шапке сайта',
            },
        ),
        migrations.CreateModel(
            name='TopNumbersRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, default='', max_length=150, verbose_name='Город')),
                ('phone', models.CharField(db_index=True, default='', max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номера телефонов справа в шапке сайта',
                'verbose_name_plural': 'Номера телефонов справа в шапке сайта',
            },
        ),
    ]
